### ISSUE TITLE
The webhook embeds the links

### ISSUE THREAD

**Issue by innosflew** [kulttuuri/discord_mediawiki#1]
For some reason the webhook embeds some of the user urls and page urls, so makes every message taking up a huge space in the Discord text channel. Is there a way to disable link embeds with the webhook?

**Comment by kulttuuri** [comment]
Can you show me screenshot of this behavior? :)

**Comment by innosflew** [comment]
Sure. Here: https://i.gyazo.com/250f413f0f7da255b96cace8c455152c.png

**Comment by kulttuuri** [comment]
Hmm, do you mean the blocks below the message on the first line, like Block/innosflev and UserRights below that? Or just the long text which is on the first row?

**Comment by innosflew** [comment]
Yeah, the blocks below that.

**Comment by kulttuuri** [comment]
That's quite interesting issue :D I didn't get the same problem. Do you have some extension enabled which shows preview of the linked website?

One thing you could try are these options:
// If this is true, pages will get additional links in the notification message (edit | delete | history).
$wgDiscordIncludePageUrls = true;
// If this is true, users will get additional links in the notification message (block | groups | talk | contribs).
$wgDiscordIncludeUserUrls = true;

Those should be added to the localsettings file. Let me know if that makes any change, I'll try to also reproduce this problem myself later today.

**Comment by innosflew** [comment]
Well, I'm not sure. I had an extension enabled winch allowed me to iframe embed an external webpage.

Also I have set $wgDiscordIncludeUserUrls and $wgDiscordIncludePageUrls to false. Sadly that disables the user urls and page urls completely, but I think I am able to live with that.

Btw, I do like when a new user sings up it shows their email, so I don't have to go check it myself. That's going to come very handy when dealing with trolls and vandals. Is there a way to show their IP address as well?

**Comment by kulttuuri** [comment]
OK - I actually got an response from Discord team. They stated this:
> Double check your settings and make sure all of the embed links are restricted for every role including @everyone.

and

> It'll be a server setting for the roles that the bot is in.

Can you see if you can find these kind of settings somewhere? I can check back later today too. About the IP thing, I can check later today if it is possible to fetch that information from mediawiki hook parameters :)

**Comment by kulttuuri** [comment]
Found it. Can you try going to your **Server Settings -> Roles -> @everyone > uncheck Embed Links** and let me know if that helps.

**Comment by innosflew** [comment]
Okay, so I went into the Server Settings and disabled Embed Links permission for every role(including the @everyone role) there is but it didn't seem to work. I've even tried go into channel setting and disable it there as well for every role but it didn't seem to work. It still embeds the links no matter what I do.

**Comment by kulttuuri** [comment]
Yep, I've asked about this from discord support. Might be bug of some sort.

**Comment by innosflew** [comment]
Hmmm, I see. Then it seems I'll will have to wait for Discord to resolve the issue. Anyways, thanks for the help. :) Also, how is the IP address fetching going?

**Comment by kulttuuri** [comment]
Didn't look at it yet :) The weird part is that I am not seeing this behavior, even though how hard I try to reproduce it. Could you invite me to your discord room so I can see the issue happening? We could also try so that you'll create new webhook, send me the url and I try to send wiki notification to it and see if that problem occurs with that, too.

**Comment by innosflew** [comment]
It's a private chat, so I'm afraid not, others wouldn't be very happy about it. But I did had a problem with webhooks before btw in an other chat. Using a service called zapier I was able to send Twitter and YouTube updates into the chat. The only problem was that this time I needed the webhook to embed the links but for some reason it suddenly just stopped embeding them. I DM'd Discord on Twitter about it and they said they had some issues with Discord but they are fixing it and after a while the links started to embed again. I also tried to make a new webhook but the problem persists, But I figured I'm going to just leave $wgDiscordIncludeUserUrls and $wgDiscordIncludePageUrls to false, so my channel wouldn't be cluttered as much with links. Also I just noticed that the mobile app of Discord doesn't supports word links. That meas a word link like this "LinkExample" will appear as this "[LinkExample](https://linkexample.com)" on mobile.

**Comment by kulttuuri** [comment]
Does the embed problem also appear on mobile btw?

**Comment by innosflew** [comment]
Yeah. This is what I see on mobile when I enable all the links: https://i.gyazo.com/d9791df3af986bd3e9c89da371ed871d.png

**Comment by kulttuuri** [comment]
Yup, mobile app doesn't seem to support markdown. Notifying discord team.

**Comment by innosflew** [comment]
Btw, I do know that only webhooks are able to do word links and only on the desktop app. When you try to add yourself in Discord for example "`[LinkExample](https://linkexample.com)`" it doesn't converts it to a word link. I looked it up and from what I've read it was a feature available to regular users as well in the past but Discord took it out because of security concerns. They maybe forgot to leave it enabled for the webhooks or maybe it was intentional to leave it enabled for those.

**Comment by AlexJFox** [comment]
FWIW I don't get this issue. I'd suspect its a Discord permissions thing. Bear in mind that Discord permissions inherit and use an odd system of grant vs. deny and are also server/channel specific based on role. I can help you out if you're having trouble.

**Comment by kulttuuri** [comment]
Yeah, this seems like odd permission issue.

On the other hand, can you give me a screenshot of how your user creation notification looks in discord? I've just tried it and I am getting blank username and email-address on the notifcation inside discord :(

**Comment by innosflew** [comment]
Here: https://i.gyazo.com/b0d9bc3ada91b920fc6783d166875fb9.png
I'm getting a blank for the real name as well, but I assumed it's blank since not everyone gives their real name during account registration because it's optional.

**Comment by kulttuuri** [comment]
FYI Added IP to latest commit :) Report back on [this thread](https://github.com/kulttuuri/discord_mediawiki/issues/2) if it's working or not.

**Comment by kulttuuri** [comment]
Marking this thread as a bug and closing. Hopefully Discord soon resolves this issue.

**Comment by kulttuuri** [comment]
@innosflew Btw did you get the extra links to be removed by adding those two configuration parameters? I've been having weird problem with my development MediaWiki and tried those settings second time now and they did not remove the links. Seems like some issue with Boolean variables (true/false) on my MediaWiki instance.
