### ISSUE TITLE
Webhook mucks up output when a page title has parentheticals

### ISSUE THREAD

**Issue by charitwo** [kulttuuri/discord_mediawiki#10]
Picture is worth a thousand words
![discord-notifications-2](https://user-images.githubusercontent.com/7400384/27512963-8ab92324-5919-11e7-8c23-05dc8ddd4e08.png)

**Comment by kulttuuri** [comment]
Ouch! That's not cool :( I'll look into that whenever I get time.

**Comment by kulttuuri** [comment]
Fixed in latest commit. Can you verify @charitwo ? :)

**Comment by charitwo** [comment]
fixed!

**Comment by kulttuuri** [comment]
Fantastic! Will close :)
