### ISSUE TITLE
Having extension enabled produces HTTP error 500 when doing null edits or touch.py on pywikibot

### ISSUE THREAD

**Issue by charitwo** [kulttuuri/discord_mediawiki#11]
Can be reproduced at https://ffxiv.gamerescape.com/wiki/Genta_Bracelet_of_Fending

Did not have issue after commenting out extension, but reproduced again after re-enabling.

![screenshot 2017-07-18 at 6 11 16 pm](https://user-images.githubusercontent.com/7400384/28343758-8a21b43e-6be4-11e7-9d0a-dd8b3f1ddd9e.png)

**Comment by charitwo** [comment]
![screenshot 2017-07-18 at 8 45 26 pm](https://user-images.githubusercontent.com/7400384/28346991-1759214c-6bfa-11e7-9e1c-8a6e000b1d43.png)

**Comment by kulttuuri** [comment]
Thanks! Will have a look when I get some free time, currently moving in to a new apartment and my time is quite limited. I'll have my own office room setup next week, will be easy to crack on this then :)

**Comment by kulttuuri** [comment]
Sorry for dropping the ball on this, been extremely busy last months. I've pushed possible fix to master. Can you try if that works?

**Comment by charitwo** [comment]
it appears to be resolved! having moved operations from IRC to discord this extension has been really helpful with relaying wiki changes!

**Comment by kulttuuri** [comment]
Fantastic :)
