### ISSUE TITLE
Internal error when changing protection level for a template

### ISSUE THREAD

**Issue by danilonobren** [kulttuuri/discord_mediawiki#12]
Hello!
First of all, thank you for the extension, it's awesome!

I'm having some issues when tryng to change a template protection even with $wgDiscordNotificationProtectedArticle as false.

![123](https://user-images.githubusercontent.com/14813304/29262089-4e888a0e-80a9-11e7-8b17-8de15c28f246.png)

**Comment by kulttuuri** [comment]
Thanks! Will try to take a look at this as soon as I can :)

**Comment by kulttuuri** [comment]
I've just tried this and it seemed to work for me. Interesting. What MediaWiki version are you using and what kind of protection settings did you try to set? Can you try setting other page protection settings with different values to see if there's some setting (like setting it only available for admins) that's causing an issue?

I tried personally with MediaWiki version 1.28.0 and couple different pages and setting all the protect options.

**Comment by kulttuuri** [comment]
Ah, I also just read that you are trying to change template protection levels? Did you mean article protection or is template protection a thing in Mediawiki? :)

**Comment by danilonobren** [comment]
I'm sorry, I guess I wasnt' clear with the "template" thing.
I'm using Mediawiki 1.29 and getting an error when trying to change a page protection to allow edits only for admins. 

I don't get any error when I leave the protection level to "allow all users", but in every other configuration, the error happens.

![123](https://user-images.githubusercontent.com/14813304/29752203-1f9bd836-8b30-11e7-89dd-0ff7fc004109.png)

**Comment by kulttuuri** [comment]
Interesting. I'll take a stab at this later today trying out similar settings. I've also hit similar problem before where it was actually MediaWiki bug. Checking out the error log you provided, it does sound bit like a bug there as for some reason it's missing a required parameter documented in mediawiki documentation (https://www.mediawiki.org/wiki/Manual:Hooks/ArticleProtectComplete)

**Comment by kulttuuri** [comment]
I just installed MediaWiki 1.29.1 and cannot reproduce this. Can you try upgrading to MediaWiki 1.29.1 as there might be bug with this on 1.29?

**Comment by danilonobren** [comment]
Hello! Thanks for the help, I'll update later today and check what happens.

**Comment by danilonobren** [comment]
I just updated my mediawiki to 1.29.1 and I still get the same error as before

Here's my Special:Version
http://spacewizard.com.br/wiki/Special:Version

Product | Version
MediaWiki | 1.29.1
PHP | 7.1.0 (apache2handler)
MySQL | 5.6.26-log
ICU | 4.2.1

Maybe something related to the PHP version?

**Comment by kulttuuri** [comment]
Ah, I think I know the problem now. I just need to set default values for those parameters. I'll create possible fix of that for you testing now.

**Comment by kulttuuri** [comment]
OK! Download latest default branch version and try with that. I added default values to all parameters in that function. No idea why it would ne required, but might be some server configuration thing that is flipped other way around than on my server.

**Comment by danilonobren** [comment]
It's everything working now! 
Thank you for the great extension :D
