### ISSUE TITLE
Backport for Mediawiki < 1.25.0?

### ISSUE THREAD

**Issue by BlinkTetris** [kulttuuri/discord_mediawiki#13]
Hi kulttuuri, 

I'm currently stuck on Mediawiki 1.16.5 due to some extensions I need that have never been updated to support later versions.  Is there any chance of backporting this extension for older versions of Mediawiki?

**Comment by kulttuuri** [comment]
Unfortunately there are no plans on doing this at the moment. I actually first started the extension codebase with older mediawiki and then ported to latest version.

Older extensions should also have some backwards compatibility, have you checked with later mediawiki version to see if the old extensions would run?
