### ISSUE TITLE
Alternate RecentChanges access

### ISSUE THREAD

**Issue by prodigion** [kulttuuri/discord_mediawiki#15]
Instead of adding hooks for every possible activity, maybe use this hook - https://www.mediawiki.org/wiki/Manual:Hooks/RecentChange_save

Alternatively, this may be an even cleaner way to push the updates: https://www.mediawiki.org/wiki/Manual:$wgRCFeeds

**Comment by kulttuuri** [comment]
Thanks! Looks good - however I currently have no time to make much changes to this extension, just minor additions / changes. Changing underlying structures to something new usually introduces new bugs. I'll however come back to this card should some of the hooks I use start deprecating or breaking in later versions of MediaWiki.
