### ISSUE TITLE
Send IP address of newly registered user to discord.

### ISSUE THREAD

**Issue by kulttuuri** [kulttuuri/discord_mediawiki#2]
Add this if possible.

**Comment by kulttuuri** [comment]
Added in 819a1e1d97676bd7421652a58aa2f37ab854356b. Someone should verify that it's working :)

**Comment by innosflew** [comment]
The IP address is showing it's working. :) https://i.gyazo.com/e5a5769596924580f64fdfaa482a8740.png
But for the real name it gives the email again for some reason.

**Comment by kulttuuri** [comment]
Fantastic. Closing :)

**Comment by kulttuuri** [comment]
Whoops. Fixed that typo in the code. Try now?

**Comment by innosflew** [comment]
Now instead of the real name it gives the username: https://i.gyazo.com/f0bdfa710cb95468764c2ba4e1b0386a.png

**Comment by innosflew** [comment]
This is what the real name supposed to be: https://i.gyazo.com/1c0d4fcd8c3997f22605280117637ab6.png

**Comment by kulttuuri** [comment]
:D

**Comment by kulttuuri** [comment]
Try now.

**Comment by innosflew** [comment]
Now everything is working perfectly. :) https://i.gyazo.com/b2499b1046fc25cbab25f6fcf6c7788d.png

**Comment by innosflew** [comment]
Oh and don't forget to update the snapshots on your extension page on mediawiki.org. Most people will going to find your extension there first.

**Comment by kulttuuri** [comment]
Yeah, did you mean this page? https://www.mediawiki.org/wiki/Extension:DiscordNotifications

If so, yes I could actually add a screenshot there of the extension for visual explanation.

**Comment by innosflew** [comment]
Yeah, the same screenshot you hav in this git would suffice, but I when I mention snapshots I was talking about the part where you can download an extension for mediawiki on their site(https://i.gyazo.com/0d1a6c3aaeaa3a928a201ff0a5a98e27.png). But I just clicked on it and it seems it redirects to this git instead of mediawiki's snapshot downloader, so no worries.

**Comment by kulttuuri** [comment]
Screenshot added 👍
