### ISSUE TITLE
Privacy and extra webhooks

### ISSUE THREAD

**Issue by innosflew** [kulttuuri/discord_mediawiki#3]
Btw, if you are looking for suggestions on what other features could be implemented in a future release, then I could suggest adding a configuration option for the LocalSettings.php that would let you turn off showing the email, real name, and the IP. Those 3 are working very good for me since I'm in a private chat, but if someone wants to configure a webhook in a public chat with your extension and they are worried about privacy it's always good to have the option to hide those. :)

And other suggestion would be maybe the option to add extra webhooks to your extension(if someone wants to add webhook wiki notifications about the same wiki into multiple chats) that could be configured independently of each other, if that's possible.

**Comment by AlexJFox** [comment]
+1 to this, really must have the option to not show IP addresses. Once a user is registered on mediawiki you need to have elevated permissions such as CheckUser to view IP addresses, It would cause great concern to people if their IP is exposed to a large Discord server as part of the registration process!

**Comment by kulttuuri** [comment]
Good idea. Will work on configuring the visibility of email / name / ip fields next.

Not sure on the extra webhook part if that would be beneficial enough.

**Comment by kulttuuri** [comment]
Latest commit should now implement this. I've also increased version number of the extension to 1.0.1. Would be great if anyone can confirm this :) @innosflew @AlexJFox 


By default we show full name, email and IP address of newly created user in the notification. You can individually disable each of these using the settings below. This is helpful for example in situation where you do not want to expose this information for users in your Discord channel:
```php
// If this is true, newly created user email address is added to notification.
$wgDiscordShowNewUserEmail = false;
// If this is true, newly created user full name is added to notification.
$wgDiscordShowNewUserFullName = false;
// If this is true, newly created user IP address is added to notification.
$wgDiscordShowNewUserIP = false;
```
