### ISSUE TITLE
Add notification on edit/move protection of an article being created/changed

### ISSUE THREAD

**Issue by AlexJFox** [kulttuuri/discord_mediawiki#4]
It would be great to be able to see notifications of any protection related edits such as when an article is newly protected or has its protection level changed.

**Comment by AlexJFox** [comment]
This is an enhancement request, seems I cannot add the label though! 😞

**Comment by kulttuuri** [comment]
Makes sense :) I'll take a stab at this whenever I can.

**Comment by kulttuuri** [comment]
Commit https://github.com/kulttuuri/discord_mediawiki/commit/16017ee887da0ef837c8caeb48eb8633110337dc adds this. Can you verify that it's working? :)

**Comment by AlexJFox** [comment]
![image](https://cloud.githubusercontent.com/assets/17463323/21326827/41959746-c624-11e6-85f1-d2569a083c78.png)

Confirmed! (I didn't specify a reason so the blank is to be expected)

Thanks!

**Comment by kulttuuri** [comment]
Fantastic :) Closing.
