### ISSUE TITLE
Deprecated or removed hooks

### ISSUE THREAD

**Issue by innosflew** [kulttuuri/discord_mediawiki#5]
Just letting you know that the following hooks have been removed in from MediaWiki core in version 1.29.0:
- https://www.mediawiki.org/wiki/Manual:Hooks/ArticleSaveComplete
- https://www.mediawiki.org/wiki/Manual:Hooks/ArticleInsertComplete

And the following hook was deprecated in version 1.27:
- https://www.mediawiki.org/wiki/Manual:Hooks/AddNewAccount

I have replaced the `ArticleInsertComplete` and the `ArticleSaveComplete` hooks in the `extension.json` file on my wiki myself, since I use the master MediaWiki core, but I thought that I should notify you in case other people who use MediaWiki 1.29 report that the extension doesn't posts article edits anymore.

**Comment by kulttuuri** [comment]
Could you do pull request for this?

**Comment by innosflew** [comment]
I haven't edited on github before but I did a pull request.

**Comment by kulttuuri** [comment]
Thanks! Closing this and moving to PR https://github.com/kulttuuri/discord_mediawiki/pull/6
