### ISSUE TITLE
New modifications

### ISSUE THREAD

**Issue by innosflew** [kulttuuri/discord_mediawiki#7]
I made some modifications to the DiscordNotifications extension I have installed on my wiki.

I converted every webhook message into rich embeds, and I also added appropriate emoji characters to each message. Furthermore, each type message not only has their own emoji to set them apart but one of my friends helped to change the color of the rich embeds depending of which type of message it's sending to the webhook.

This is how they look like:
![76de556ee696b13ff1557021022e6c75](https://cloud.githubusercontent.com/assets/18039193/23768623/f0ecc49a-050c-11e7-8ded-0e109dfb7b1b.png)
![ad8c60f2d6ec460509ef4b5db7123046](https://cloud.githubusercontent.com/assets/18039193/23768678/18328ac6-050d-11e7-94ac-b3edb062fa75.png)
![f00ff372e751063fe5ba97e372f6918c](https://cloud.githubusercontent.com/assets/18039193/23768714/32d9f30a-050d-11e7-9655-a5304f23e917.png)
![62adea529b4692c58f6115c3cd887cfc](https://cloud.githubusercontent.com/assets/18039193/23768799/7b13e464-050d-11e7-9cee-b462fa1f0752.png)
![6af62b924a261440805d3f4196d6ed37](https://cloud.githubusercontent.com/assets/18039193/23768869/b3c8b97e-050d-11e7-8d01-c6d712d1c475.png)
![9f28279ef620ff0ae9d8387d90855d2e](https://cloud.githubusercontent.com/assets/18039193/23768921/e380d1ce-050d-11e7-8125-03be5b1dd4a6.png)
![0b8ae52d449fce828ba62925843dc9ae](https://cloud.githubusercontent.com/assets/18039193/23768958/062cfdce-050e-11e7-96dd-c6f47a1e9209.png)
![48f0f5ced4970d1ed7ccb96641c86e22](https://cloud.githubusercontent.com/assets/18039193/23769022/3de083da-050e-11e7-901c-e7a1b97f693f.png)

My friend also helped to fix an error in the link of the upload file message.
Before:
![ebe10451c97f652b65419f3dd01ea120](https://cloud.githubusercontent.com/assets/18039193/23769348/5e810244-050f-11e7-8e09-7d5d826c6668.png)
After:
![771644b32fe8cd39a009e225f6f95a68](https://cloud.githubusercontent.com/assets/18039193/23769453/bc5b24bc-050f-11e7-8e26-f1f6b220f9b7.png)

Would you like to merge this with your version?

**Comment by kulttuuri** [comment]
That's fantastic. Yeah, can you do pull request for this?

**Comment by innosflew** [comment]
Sure :)

**Comment by kulttuuri** [comment]
Now also in releases: https://github.com/kulttuuri/discord_mediawiki/releases/tag/v1.0.3
